### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by Tobe2d** [nianticlabs/ace#1]
Any chance for windows users?

**Comment by tcavallari** [comment]
Hello, thanks for your question. Unfortunately we have no plans to support Windows.

----------------

That said, PyTorch [has Windows support](https://pytorch.org/get-started/locally/), so it should be possible to create a different conda environment that works there. 

Anyways, you can start with: 
```
conda create --name ace python=3.8
conda activate ace
conda install pytorch=2.0.0 torchvision=0.15.0 pytorch-cuda=11.8 -c pytorch -c nvidia
conda install scikit-image
conda install -c conda-forge opencv=4.4
conda install -c conda-forge trimesh
conda install -c conda-forge pyrender
conda install -c anaconda libglu
conda install -c conda-forge matplotlib
```
and adapt the packages/versions to use variants that are available on Windows.

Building the C++/Python bindings (in the `dsacstar` folder) might require some work, but we didn't use anything Linux-specific, so they _should_ work on Windows, eventually.

**Comment by ebrach** [comment]
Regarding the `dsacstar` bindings: They are not too different from the [NG-RANSAC ](https://github.com/vislearn/ngransac) bindings. Someone has successfully ported those to Windows 10 and documented their process here: https://github.com/vislearn/ngransac/issues/21

Some of that will have to be adjusted because the library versions are different (e.g. NG-RANSAC uses an older version of OpenCV). But maybe it can serve as a template.

**Comment by tcavallari** [comment]
Closing for now.
