### ISSUE TITLE
Consistency in pose format for train/validation

### ISSUE THREAD

**Issue by hazel-sudz** [nianticlabs/ace#14]
It seems to me that the training data wants poses in a 4x4 rotation/translation matrix and the evaluation wants the pose rotation in a quaternion format.  For the sake of consistency, would it make sense for these two formats to be aligned?

**Comment by tcavallari** [comment]
Hello, the reason why the ACE codebase uses two different pose conventions for input and output is mostly historical, since the code is based on the [DSAC* repository](https://github.com/vislearn/dsacstar) where the input and output formats were already defined that way.

That said, the reason why the original output format was defined as quat+translation is because that's what was used by the COLMAP project (and also in the [codebase](https://github.com/tsattler/visloc_pseudo_gt_limitations#pose-files) of the ICCV 2021 paper "On the Limits of Pseudo Ground Truth in Visual Camera Re-Localization"), so it makes it easier to use the ACE poses in downstream tasks, if needed.

We don't have plans to make significant changes to this repository, as it's mostly intended to replicate the results we presented in the ACE paper, and modifying the pose representation wouldn't add much to the framework in practical terms.
