### ISSUE TITLE
Question about sensitivity to ground truth pose accuracy

### ISSUE THREAD

**Issue by hazel-sudz** [nianticlabs/ace#19]
Hi, 

We have been playing around with this approach trying to train models from data supplied by ArKit on iphones. Unfortunately, we have not been able to achieve good results by trying to localize 20 seconds worth of frames against 20 seconds worth of mapping frames (around 30fps). The data is recorded by physically aligning the phone from the same place. The median rotation error is usually above 30 degrees and the translation error is around 50-100 cm while indoors in a small room. 

I'm wondering if you have any speculation on what the problem might be. It's clear that the poses provided by ArKit are not fully accurate as they are running their own black box SLAM system. However, they are generally consistent over time. Is it really possible that a few percentage points of error on the ground truth can blow up the model error by this much? 

Thank you so much

**Comment by tcavallari** [comment]
Hello.

We regularly use data with ARKit/ARCore poses (see the Wayspots dataset, for example), and we had generally good results even though the poses, as you mentioned, are not perfect.

I have a couple suggestions for you to try and investigate the issue.

First, can you try creating a visualization of the training and testing process? You can use the `--render_visualization` flag in the train/test scripts (https://github.com/nianticlabs/ace#ace-training) to save a video showing the evolution of the trained network over the course of the training, and the predicted poses during testing.
That should:
- tell you whether the network is learning anything useful (the point cloud will rougly look like the scene) or it's just random.
- allow you to visualize the camera poses relative to the point cloud, to make sure your ground truth is good enough and there isn't a coordinate system error (flipped axis or similar issue).

If the output from the above suggestion seems reasonable, you could look into the inlier count for each predicted camera pose.
The metrics for the datasets we experimented with (7Scenes/12Scenes/etc...) measure the error over all the predicted pose, there isn't a concept of "recall" but, in practice, you can filter results by inlier count ([see the replies to this thread](https://github.com/nianticlabs/ace/issues/4#issuecomment-1568157206)) and return a failure instead of a pose which is grossly incorrect, since that's probably preferable.

As Eric said, estimates with inlier count below 100 are rarely trustworthy, whereas if the inlier count is above 400 then the results are typically pretty good.

**Comment by hazel-sudz** [comment]
Managed to catch an issue of inverted axis by running the visualizer that was messing with the results. Works perfectly now, thank you so much for the awesome model @tcavallari. Our rotation error now hovers around 0-2 degree and translation hovers around 5cm which is wonderful!

The point cloud looks strikingly similar to the scene. When looking at a table, it's even possible to make out objects like laptops and backpacks :)

**Comment by hazel-sudz** [comment]
Summary results when we fed posed ARKit images walking around a table with some objects on it: 

```
INFO:__main__:===================================================
INFO:__main__:Test complete.
INFO:__main__:Accuracy:
INFO:__main__:  10cm/5deg: 98.0%
INFO:__main__:  5cm/5deg: 78.4%
INFO:__main__:  2cm/2deg: 20.3%
INFO:__main__:  1cm/1deg: 3.4%
INFO:__main__:Median Error: 0.7deg, 3.7cm
```
