### ISSUE TITLE
Custom Dataset.

### ISSUE THREAD

**Issue by shaziagul-rgb** [nianticlabs/ace#2]
Thank you for releasing the code. Can you please guide, how to generate Output map file  on custom dataset? I tried running the code on my custom dataset and it is showing following error. Once again thank you.

serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'

**Comment by tcavallari** [comment]
Hello, thanks for your question.

First of all, the `UnpicklingError` could be due to the fact the `ace_encoder_pretrained.pt` file (which is a git LFS file) hasn't been checked out correctly. Please double check the file size and contents. It should be binary and ~21MB. If it's a small text file, then you'll need to make sure LFS is configured correctly on your environment (see here: https://github.com/nianticlabs/ace/tree/main#installation).

If the LFS file is not the actual issue, from that error message it's hard to tell what is going wrong. Could you please paste the full message (including stack trace), and a minimal code example to reproduce the issue?

**Comment by shaziagul-rgb** [comment]
Hello, thank you for your guidance. I have rechecked and the ace_encoder_pretrained.pt is 22.3 MB, which looks that its completely downloaded. I passed the following command. 

./train_ace.py datasets/OW output/ace_encoder_pretrained.pt

My custom Dataset names OW has all the train files available. The folder has sub folders with (rgb, poses, calibration and init files). 

It still doesn't run and gave me the following error.

INFO:ace_trainer:Loaded training scan from: datasets/OW -- 579 images, mean: 0.08 0.04 -0.09
Traceback (most recent call last):
  File "./train_ace.py", line 126, in <module>
    trainer = TrainerACE(options)
  File "/home/shazia/ace/ace_trainer.py", line 92, in __init__
    encoder_state_dict = torch.load(self.options.encoder_path, map_location="cpu")
  File "/home/shazia/anaconda3/envs/ace/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/shazia/anaconda3/envs/ace/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.


Can you please look into this error and let me know that if I am doing something wrong? Looking forward. Thank you

**Comment by ebrach** [comment]
Not sure this is the issue, but the second argument of `./train_ace.py` is supposed to be the file name under which the new map should be stored. In your call, it looks like you are trying to pass the encoder weights as second argument.

Make sure the encoder weights are in the same folder as `./train_ace.py`. If so, the script will find them automatically. Use the second argument to specify the output file. E.g.

`./train_ace.py datasets/OW output/ace_map_ow.pt`

**Comment by shaziagul-rgb** [comment]
Thank you for your hep. I done the training. It again showing some issue with the testing. When I ran the test command. It doesn't produce anything in the text file and shows the following error. Can you please look into this.

INFO:__main__:Test images found: 27
INFO:__main__:Loaded encoder from: ace_encoder_pretrained.pt
INFO:__main__:Loaded head weights from: output/ace_encoder_ow.pt
INFO:ace_network:Creating regressor from pretrained state_dict:
	Num head blocks: 1
	Homogeneous coordinates: True
	Encoder feature size: 512
INFO:__main__:Saving test aggregate statistics to: output/test_OB_.txt
INFO:__main__:Saving per-frame poses and errors to: output/poses_OB_.txt
Traceback (most recent call last):
  File "./test_ace.py", line 222, in <module>
    inlier_count = dsacstar.forward_rgb(
AttributeError: module 'dsacstar' has no attribute 'forward_rgb'

**Comment by shaziagul-rgb** [comment]
Awesome! Thank you so much for guidance..

**Comment by shaziagul-rgb** [comment]
Thank you in Advance. I have a question about translation and rotation error. What is the threshold for these error? How do we know that this error is the limit for localization successful or not successful. Suppose if I send a camera frame, I then want to check that the camera is correctly localised or not. Suppose the ACE gaves me 10 cm translation error. Does it mean that it is not localised? Can you please explain the threshold? and Also can you please let me know how to know the pose accuracy of ace?

**Comment by ebrach** [comment]
It is up to you to decide what pose you accept as "good enough" compared to ground truth. The thresholds that are used in papers are somewhat arbitrary and depend on the dataset. For indoor scenes, people normally accept a pose as "good" if its below 5cm position error and 5deg rotation error. For outdoor datasets, people normally deploy looser thresholds, e.g. on Wayspots we use 10cm and 5deg, and on the much larger Aachen dataset, thresholds start at 25cm. 

The median pose error over the entire test set can serve as an indication of the general accuracy that you can expect. But note that the median is robust to 50% outlier estimates. So the median does not tell you how robust the method is because it hides up to 50% bad estimates. And the median can also return non-sensical results if your outlier rate is higher than 50% - e.g. for very difficult scenes.
