### ISSUE TITLE
fx and fy in test_ace.py

### ISSUE THREAD

**Issue by RohanChacko** [nianticlabs/ace#26]
Can the following line be removed since different `fx` and `fy` is supported after #15?
https://github.com/nianticlabs/ace/blob/6b2a3bf2d3d2988041b8fb401c1fb5c872e49ee9/test_ace.py#L213

**Comment by RohanChacko** [comment]
This line needs to be modified accordingly as well (assuming image isn't square) https://github.com/nianticlabs/ace/blob/6b2a3bf2d3d2988041b8fb401c1fb5c872e49ee9/dataset.py#L379

**Comment by tcavallari** [comment]
Apologies for the delayed reply.

Changing the lines mentioned above wouldn't be enough, as the python/C++ bindings at the moment expect a single focal length (see [here](https://github.com/nianticlabs/ace/blob/main/dsacstar/dsacstar.cpp#L69)).

In order for someone to use intrinsics that have different focal lengths for x and y it would be necessary to update the C++ code as well. Since the code internally uses OpenCV I suspect it wouldn't be too complicated: one needs to properly define the calibration matrix passed to the various CV functions, and it should just work; but we have not tested it.
