### ISSUE TITLE
Reprojection Error

### ISSUE THREAD

**Issue by shaziagul-rgb** [nianticlabs/ace#32]
Could you please explain to me what the reprojection error shows on the right side of the video during mapping?

**Comment by tcavallari** [comment]
It's simply meant as a _qualitative_ indicator of the distribution of reprojection errors within the pixels in each training batch. 

Since during training we aim to minimise the pixel-wise reprojection error, the goal is to see the mass in the histogram "move" to the right during the course of the training. That indicates that the network is learning the structure of the scene over time.

**Comment by shaziagul-rgb** [comment]
Thank you so much for your answer.

**Comment by shaziagul-rgb** [comment]
Thanks
