### ISSUE TITLE
custom data evaluation

### ISSUE THREAD

**Issue by minhlenhat21** [nianticlabs/ace#38]
hi ace team, thanks for great work.
I'm currently using ace model for my custom data. But some scene, the result is looking good, 12.4cm distance error and 4.4 degree angle error but there are a lot of scene that have a huge error. I suppose that is because of the way i recorded the training data. Is there any solution to check if i recorded video correctly (does it covers good part, the features is good ...) in realtime when i record the video training ?

**Comment by ebrach** [comment]
Hi! We are not aware of such a tool, although it would be handy! The best we have in ACE is the visualisation of the mapping process which at least shows you the camera poses you are training with, and you can judge whether they look plausible. Otherwise, ACE might struggle if your environment is very large and/or contains repeating structures. For large environments, we would recommend to try the ensemble version of ACE, as we did on Cambridge Landmarks.

Best,
Eric
