### ISSUE TITLE
Support in MacOS

### ISSUE THREAD

**Issue by keepgoing2996** [nianticlabs/ace#8]
Is there any support to build dsacstar in macos?
How can I specify opencv_inc_dir if using own python environment?  Is it c++ opencv or python opencv? Thanks

**Comment by tcavallari** [comment]
Hello! Thanks for your question, unfortunately we don't plan to explicitly support MacOS. 

Still, I'll try to answer your question to the best of my knowledge.

>  Is it c++ opencv or python opencv

The `dsacstar` bindings require the C++ version of OpenCV, but there are some parts of the Python code that require OpenCV as well (we have a few `import cv2` in our scripts). The OpenCV package installed by conda (see [this](https://github.com/nianticlabs/ace/issues/1) to create a conda environment from scratch, without using our provided `environment.yml`, since that's Linux-specific) provides both interfaces but, if you use a custom python environment, you'll have to make sure both the C++ libraries/includes/etc... and the `cv2` Python classes are available.

One thing to  note: the network training/inference code requires cuda at the moment. I know that recently PyTorch introduced a rudimental support for Metal so you could change our code to use it, but I've never tested it, and don't know how well it works (or if at all).

**Comment by tcavallari** [comment]
Closing for now. Happy to continue the discussion if more questions come up.
